# Site settings
name: wonder's home
email: yananwang09@gmail.com
author: yananwang09
url: 'https://yananwang09.github.io/wonder.github.io/'
resume_site: 'https://yananwang09.github.io/wonder.github.io/'
github: https://github.com/yananwang09/wonder.github.io
baseurl: 'wonder.github.io/'
description: Actually, less is more!
meta_description: 王亚楠;个人博客;学而不思则罔;思而不学则殆;开始玩
motto: I know nothing except the fact of my ignorance
banner: 学而不思则罔，思而不学则殆。

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: yananwang09
highlighter: Pygments

# Build settings
markdown: kramdown

baidu_analysis: ''

